[package]
authors = ["Orhan Balci <orhanbalci@gmail.com>"]
name = "steering"
version = "0.1.0"

[dependencies]
alga = "*"
derive_builder = "0.3.0"
nalgebra = "*"
num-traits = "*"

[dev-dependencies]
termion = "*"
tui = "*"
